spring:
  profiles:
    active: dev,db
  application:
    name: my-project-admin-client
  boot:
    admin:
      client:
        url: http://localhost:7777

#开放端点用于SpringBoot Admin的监控
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


logging:
  file:
    name: my-project-admin-client.log #配置生成日志文件名称